name: Playwright UI Automation
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "select the Environment to run the tests against"
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
          - aci

permissions:
  contents: write

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install npm & playwright dependencies
        run: |
          npm install 
          npx playwright install-deps
          npx playwright install
          npx playwright install --force chrome
      

      - name: Clean old Allure results
        run: rm -rf allure-results allure-report

      - name: Run Playwright Tests
        run: |
         ENV=${{ github.event.inputs.environment }} xvfb-run -a npm run test:tag

      - name: Generate Allure Report
        if: always()
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        run: |
          mkdir -p /tmp/allure-report
          cp -r allure-report/* /tmp/allure-report/

          git reset --hard
          git fetch origin || true
          git checkout gh-pages || git checkout -b gh-pages

          for item in * .*; do
            if [ "$item" != "." ] && [ "$item" != ".." ] && [ "$item" != ".git" ]; then
              rm -rf "$item"
            fi
          done

          cp -r /tmp/allure-report/* .
          touch .nojekyll

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "Publish Playwright Allure report"
          git push origin gh-pages
